# Generated by Django 3.2.9 on 2021-11-17 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFormulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_filepath', models.CharField(max_length=100)),
                ('formula_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('active', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TakeQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userQuizScore', models.IntegerField(default=0)),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.quiz')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='TakeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAnswer', models.FloatField(default=None)),
                ('correct', models.BooleanField(default=False)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.quiz')),
                ('takeQuizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.takequiz')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FloatField()),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.quiz')),
                ('quizQuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_app.quizquestion')),
            ],
        ),
    ]
